---
- name: upload inventory
  copy: src={{ inventory_file_source }} dest=/home/{{ undercloud_user }}/nodes.json
  tags:
    - setup
  become_user: "{{ undercloud_user }}"

- name: import and introspect inventory
  shell: |
      source ~/stackrc
      openstack overcloud node import --introspect --provide nodes.json
  tags:
    - setup
  become_user: "{{ undercloud_user }}"
