---
- get_url:
    url: https://trunk.rdoproject.org/centos7-master/current-passed-ci/delorean.repo
    dest: /etc/yum.repos.d/delorean.repo
  tags:
    - setup

- get_url:
    url: http://trunk.rdoproject.org/centos7/current-passed-ci/delorean.repo
    dest: /etc/yum.repos.d/delorean-current.repo
  tags:
    - setup

- get_url:
    url: http://trunk.rdoproject.org/centos7/delorean-deps.repo
    dest: /etc/yum.repos.d/delorean-deps.repo
  tags:
    - setup

- name: fixup delorean-current
  shell: |
    sudo sed -i 's/\[delorean\]/\[delorean-current\]/' /etc/yum.repos.d/delorean-current.repo
  tags:
    - setup

- name: update includepkgs for delorean-current.repo
  lineinfile:
    dest: /etc/yum.repos.d/delorean-current.repo
    line: >
      includepkgs=diskimage-builder,instack,instack-undercloud,os-apply-config,os-cloud-config,os-collect-config,os-net-config,os-refresh-config,python-tripleoclient,openstack-tripleo-common,openstack-tripleo-heat-templates,openstack-tripleo-image-elements,openstack-tripleo,openstack-tripleo-puppet-elements,openstack-puppet-modules,puppet-*
  tags:
    - setup
